server:
  tomcat:
    uri-encoding: UTF-8

upload:
  # 默认值，实际会被 profile 覆盖
  path: ${UPLOAD_PATH:uploads}

spring:
  # 路径映射： 通过配置文件实现
  web:
    resources:
      static-locations:
        - classpath:/static/
        - file:${upload.path}
  profiles:
    active: dev
  application:
    name: springboot3
  servlet:
    encoding:
      charset: utf-8
      enabled: true
      force: true